# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Cornish spellchecker"
kw = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Cornish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
kw = "TRANSLATE: A spellchecker for Cornish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kw"

[windows]
system_product_code = "{C9F15A96-150C-40F5-851F-FC5F26E5D59D}_is1"
legacy_product_codes = [
    { value = "4545B4D7-E474-47CD-81D1-99A7703ECEA1", kind = "nsis" },
    { value = "5A2E2DCA-5769-42FB-8D21-C005E4A32D0A", kind = "nsis" }
]

[package.speller]
name = "Cornish"
version = "0.1.1"

[package.grammar]
name = "Cornish"
version = "0.1.0"

[package.tts-text-proc]
name = "Cornish"
version = "0.1.0"

[package.hyphenator]
name = "Cornish"
version = "0.1.0"
