template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "corn1251"
__REPO__ = "lang-cor"
__UND2C__ = "kw"
__UNDEFINED__ = "Cornish"
__UND__ = "cor"
