template = "https://github.com/giellalt/template-lang-und"
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "corn1251"
__REPO__ = "lang-cor"
__UND2C__ = "kw"
__UNDEFINED__ = "Cornish"
__UND__ = "cor"
